# Generated by Django 2.1 on 2018-09-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileTree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parentId', models.IntegerField()),
                ('level', models.IntegerField(null=True)),
                ('name', models.TextField(max_length=60)),
                ('type', models.CharField(max_length=32)),
                ('modifyTime', models.DateTimeField(auto_now=True, null=True)),
                ('userId', models.IntegerField(null=True)),
            ],
        ),
    ]
